[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "retreat:launch2025" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200