backend:
  name: github
  repo: carmaretreats/retreats
  branch: add-decap-cms

media_folder: "public/uploads"    # Carpeta donde se guardan las imágenes en el repo
public_folder: "/uploads"         # Ruta pública para servir las imágenes

collections:
  - name: "testpage"                 # Identificador interno de la colección
    label: "CMS Preview Page"        # Título que se verá en el panel del CMS
    files:
      - file: "src/pages/cms-preview.astro"   # Página que se va a editar
        label: "CMS Preview"
        name: "cms_preview"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }