publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "landingpage"
    label: "Carma Retreats Landing Page CMS"
    files:
      - file: "src/content/retreats-page.json"
        label: "Retreats Page Content"
        name: "retreats"
        format: "json"
        fields:
          - label: "FAQ Section"
            name: "faqSection"
            widget: "object"
            fields:
              - { label: "Section ID", name: "id", widget: "string", default: "faq" }
              - { label: "Section Label", name: "sectionLabel", widget: "string" }
              - { label: "Heading", name: "heading", widget: "string" }
              - label: "Left Column FAQs"
                name: "faqsLeft"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Question", name: "question", widget: "string" }
                  - { label: "Answer", name: "answer", widget: "text" }
              - label: "Right Column FAQs"
                name: "faqsRight"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Question", name: "question", widget: "string" }
                  - { label: "Answer", name: "answer", widget: "text" }
              - label: "CTA"
                name: "cta"
                widget: "object"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Link", name: "href", widget: "string" }
          - label: "Mini Gallery Section"
            name: "miniGallery"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Section ID", name: "id", widget: "string", default: "mini-gallery" }
              - { label: "Title", name: "title", widget: "string", default: "Mini Gallery" }
              - label: "Images"
                name: "images"
                widget: "list"
                summary: "{{fields.alt}}"
                fields:
                  - { label: "Image", name: "src", widget: "image" }
                  - { label: "Alt text", name: "alt", widget: "string" }
          # === RETREATS SECTION ===
          - label: "Retreats"
            name: "retreats"
            widget: "list"
            min: 2
            max: 2
            summary: "{{fields.title}}"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Month", name: "month", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - label: "Accommodation Options"
                name: "accommodationOptions"
                widget: "list"
                field: { label: "Option", name: "option", widget: "string" }

          # === KONTAKT SECTION ===
          - label: "Kontakt Section"
            name: "kontakt"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Section ID", name: "id", widget: "string" }
              - { label: "Section Label", name: "sectionLabel", widget: "string" }
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Form"
                name: "form"
                widget: "object"
                fields:
                  - label: "Retreat Field"
                    name: "retreat"
                    widget: "object"
                    fields:
                      - { label: "Type", name: "type", widget: "string" }
                      - { label: "Label", name: "label", widget: "string" }
                  - label: "Accommodation Field"
                    name: "accommodation"
                    widget: "object"
                    fields:
                      - { label: "Type", name: "type", widget: "string" }
                      - { label: "Label", name: "label", widget: "string" }
                  - label: "Name Field"
                    name: "name"
                    widget: "object"
                    fields:
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "Placeholder", name: "placeholder", widget: "string" }
                      - { label: "Error Message", name: "errorMessage", widget: "string" }
                  - label: "Email Field"
                    name: "email"
                    widget: "object"
                    fields:
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "Placeholder", name: "placeholder", widget: "string" }
                      - { label: "Error Message", name: "errorMessage", widget: "string" }
                  - label: "Message Field"
                    name: "lead_message"
                    widget: "object"
                    fields:
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "Placeholder", name: "placeholder", widget: "string" }
                  - label: "Submit Button"
                    name: "submitButton"
                    widget: "object"
                    fields:
                      - { label: "Label", name: "label", widget: "string" }